# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: test-workflows

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - actions/**
      - custard/**
      - scripts/**
  pull_request:
    paths:
      - .github/**
      - actions/**
      - custard/**
      - scripts/**
  workflow_run:
    workflows:
      - Custard CI # .github/workflows/custard-ci.yaml
    types:
      # There's no need to wait for the "submit job" to finish.
      # As long as it's "in_progress", it means it has been approved.
      - in_progress
  workflow_dispatch:
    inputs:
      run-all:
        description: Run all tests
        type: boolean
        default: false
      paths:
        description: Comma separated packages to test
        type: string
      ref:
        description: Branch, tag, or commit SHA to run tests on
        type: string
        default: origin/main

jobs:
  github-context:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # For debugging information.
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo "$INPUTS"
        env:
          INPUTS: ${{ toJson(inputs) }}

  affected:
    uses: ./.github/workflows/affected.yaml
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      config-file: .github/test/config.jsonc
      paths: ${{ (inputs.run-all && '.') || inputs.paths || '.github/test/pkg1' }}
      create-check-if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      check-name: Custard CI (create-check on ${{ (github.event.workflow_run && 'workflow_run') || (github.event.pull_request && 'pull_request') || (inputs && 'workflow_dispatch') }})
      timeout-minutes: 1

  setup-custard:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.affected.outputs.paths) }}
    continue-on-error: true
    timeout-minutes: 1
    env:
      NODE_OPTIONS: --no-warnings=75058
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      - name: Check queued
        uses: ./actions/steps/create-check
        id: in_progress
        with:
          sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
          name: workflows / ${{ github.job }} (${{ matrix.path }}) (create-check on ${{ (github.event.workflow_run && 'workflow_run') || (github.event.pull_request && 'pull_request') || (inputs && 'workflow_dispatch') }})
          job-name: ${{ github.job }} (${{ matrix.path }})
          status: in_progress
          if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: "24"
      - name: Setup Custard
        uses: ./actions/steps/setup-custard
      - name: Run Custard
        run: node custard.ts run .github/test/config.jsonc test ${{ matrix.path }}
      - name: Check success
        uses: ./actions/steps/update-check
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: success
      - name: Check failure
        uses: ./actions/steps/update-check
        if: failure()
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: failure

  done:
    needs: [affected, setup-custard]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      - name: Check success
        uses: ./actions/steps/update-check
        with:
          check: ${{ needs.affected.outputs.check }}
          status: success

  map-run:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
      - name: Check in_progress
        uses: ./actions/steps/create-check
        id: in_progress
        with:
          sha: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || inputs.ref || github.sha }}
          status: in_progress
          name: workflows / ${{ github.job }} (create-check on ${{ (github.event.workflow_run && 'workflow_run') || (github.event.pull_request && 'pull_request') || (inputs && 'workflow_dispatch') }})
          if: ${{ !!github.event.workflow_run || (github.event.pull_request && !github.event.pull_request.head.repo.fork) }}
      - name: Run command on affected paths
        uses: ./actions/steps/map-run
        with:
          command: ls -lh
          paths: ${{ needs.affected.outputs.paths }}
          outputs-always: true
      - name: Check success
        uses: ./actions/steps/update-check
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: success
      - name: Check failure
        uses: ./actions/steps/update-check
        if: failure()
        with:
          check: ${{ steps.in_progress.outputs.check }}
          status: failure
